from collections.abc import Callable

import numpy as np
import torch

from phlower_tensor._base import PhysicalDimensions

def phlower_dimension_tensor(
    values: dict[str, float] | PhysicalDimensions,
    dtype: torch.dtype = torch.float32,
    device: str | torch.device | None = None,
) -> PhlowerDimensionTensor: ...
def zero_dimension_tensor(
    device: str | torch.device | None,
) -> PhlowerDimensionTensor: ...

class PhlowerDimensionTensor:
    @classmethod
    def from_list(
        cls,
        values: list[float] | tuple[float],
        dtype: torch.dtype = torch.float32,
        device: str | torch.device | None = None,
    ) -> PhlowerDimensionTensor: ...
    def __sub__(self, __value: object) -> PhlowerDimensionTensor: ...
    def __rsub__(self, __value: object) -> PhlowerDimensionTensor: ...
    def __add__(self, __value: object) -> PhlowerDimensionTensor: ...
    def __radd__(self, __value: object) -> PhlowerDimensionTensor: ...
    def __mul__(self, __value: object) -> PhlowerDimensionTensor: ...
    def __rmul__(self, __value: object) -> PhlowerDimensionTensor: ...
    def __truediv__(self, __value: object) -> PhlowerDimensionTensor: ...
    def __rtruediv__(self, __value: object) -> PhlowerDimensionTensor: ...
    def __eq__(self, other: object) -> bool: ...
    def __pow__(self, other: float | int) -> PhlowerDimensionTensor: ...
    def __repr__(self) -> str: ...
    def to_physics_dimension(self) -> PhysicalDimensions: ...
    def to_dict(self) -> dict[str, float]: ...
    def to(
        self,
        device: str | torch.device | None = None,
        non_blocking: bool = False,
        dtype: torch.dtype | None = None,
    ) -> PhlowerDimensionTensor: ...
    def detach(self) -> PhlowerDimensionTensor: ...
    def clone(self) -> PhlowerDimensionTensor: ...
    @property
    def dtype(self) -> torch.dtype: ...
    @property
    def device(self) -> torch.device: ...
    @property
    def is_dimensionless(self) -> bool: ...
    def numpy(self) -> np.ndarray: ...
    @classmethod
    def __torch_function__(
        cls,
        func: Callable,
        types: list[type],
        args: tuple,
        kwargs: dict | None = None,
    ) -> PhlowerDimensionTensor: ...

PhysicDimensionLikeObject = (
    PhysicalDimensions
    | PhlowerDimensionTensor
    | torch.Tensor
    | dict[str, float]
    | list[float]
    | tuple[float]
)
